apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - identity-service.yaml
  - properties-service.yaml
  - ingestion-service.yaml
  - analytics-service.yaml
  - analytics-worker.yaml

