apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: agrosolutions-observability
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        isDefault: true
        url: http://prometheus:9090
        editable: true
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: AgroSolutions
        orgId: 1
        folder: AgroSolutions
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards

