apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: agrosolutions-app
type: Opaque
stringData:
  postgres-user: "postgres"
  postgres-password: "postgres"
  postgres-identity-conn: "Host=postgres;Port=5432;Database=agrosolutions_identity;Username=postgres;Password=postgres"
  postgres-properties-conn: "Host=postgres;Port=5432;Database=agrosolutions_properties;Username=postgres;Password=postgres"
  postgres-analytics-conn: "Host=postgres;Port=5432;Database=agrosolutions_analytics;Username=postgres;Password=postgres"
  mongodb-conn: "mongodb://mongodb:27017"
  rabbitmq-host: "rabbitmq"
  rabbitmq-username: "admin"
  rabbitmq-password: "admin123"
  rabbitmq-default-user: "admin"
  rabbitmq-default-pass: "admin123"
  jwt-secret-key: "AgroSolutions-SecretKey-For-JWT-Token-Generation-2024"
  jwt-issuer: "AgroSolutions.Identity.Service"
  jwt-audience: "AgroSolutions"
  jwt-expiration-minutes: "1440"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: agrosolutions-observability
type: Opaque
stringData:
  admin-user: "admin"
  admin-password: "admin"

